
stages:
  - test
  - build
  - format
  - doc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Test::MacOS:
  stage: test
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[debug]/'
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B build -G Xcode -DPARTIELS_BUILD_TAG=$CI_COMMIT_TAG -DPARTIELS_BUILD_ID=$CI_PIPELINE_ID
    - ./Scripts/macos-build.sh Debug
    - ctest -C Debug -VV --test-dir build 

Test::Windows:
  stage: test
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[debug]/'
  tags:
    - windows
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B build -G "Visual Studio 17 2022" -A x64 -DTIMESTAMP_SERVER_URL="http://timestamp.digicert.com" -DPARTIELS_BUILD_TAG="$CI_COMMIT_TAG" -DPARTIELS_BUILD_ID="$CI_PIPELINE_ID"
    - cmake --build build --config Debug
    - ctest -C Debug -VV --test-dir build 

Test::Linux:
  stage: test
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[debug]/'
  tags:
    - linux
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DPARTIELS_BUILD_TAG=$CI_COMMIT_TAG -DPARTIELS_BUILD_ID=$CI_PIPELINE_ID
    - cmake --build build
    - ctest -C Debug -V --test-dir build 

Build::MacOS:
  stage: build
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B build -G Xcode -DPARTIELS_BUILD_TAG=$CI_COMMIT_TAG -DPARTIELS_BUILD_ID=$CI_PIPELINE_ID
    - ./Scripts/macos-build.sh Release
    - ctest -C Release -VV --test-dir build 

Build::Windows:
  stage: build
  tags:
    - windows
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B build -G "Visual Studio 17 2022" -A x64 -DTIMESTAMP_SERVER_URL="http://timestamp.digicert.com" -DPARTIELS_BUILD_TAG="$CI_COMMIT_TAG" -DPARTIELS_BUILD_ID="$CI_PIPELINE_ID"
    - cmake --build build --config Release
    - move-item -path ".\build\Partiels-install.exe" -destination ".\"
    - ctest -C Release -VV --test-dir build 
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Partiels-install.exe
    expire_in: 1 week

Build::Linux:
  stage: build
  tags:
    - linux
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DPARTIELS_BUILD_TAG=$CI_COMMIT_TAG -DPARTIELS_BUILD_ID=$CI_PIPELINE_ID
    - cmake --build build
    - ctest -C Release -V --test-dir build 
    - $CI_PROJECT_DIR/Scripts/linux-package.sh $CI_PROJECT_DIR/Partiels
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Partiels/
    expire_in: 1 week

Format:
  stage: format
  tags:
    - osx
  needs: []
  before_script:
    - brew install clang-format
  script:
    - find Source -iname *.h -o -iname *.cpp | xargs clang-format --Werror --dry-run --verbose -style=file
    - find Dependencies/Misc/Source -iname *.h -o -iname *.cpp | xargs clang-format --Werror --dry-run --verbose -style=file
    - find VampPlugins -iname *.h -o -iname *.cpp | xargs clang-format --Werror --dry-run --verbose -style=file

Doc:
  stage: doc
  tags:
    - osx
  needs: []
  before_script:
    - npm install mdpdf -g
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B build -G Xcode -DPARTIELS_BUILD_TAG=$CI_COMMIT_TAG -DPARTIELS_BUILD_ID=$CI_PIPELINE_ID
    - cmake --build build --target PartielsManual -- -quiet
    - mv build/Partiels-Manual.pdf ./Partiels-Manual.pdf
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Partiels-Manual.pdf
    expire_in: 1 week
