
stages:
  - test
  - build
  - format
  - doc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Test::MacOS:
  stage: test
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -G Xcode
    - ../Scripts/macos-build.sh Debug
    - ctest -C Debug -VV

Test::Windows:
  stage: test
  tags:
    - windows
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 17 2022" -A x64 -DTIMESTAMP_SERVER_URL="http://timestamp.digicert.com"
    - cmake --build . --config Debug
    - ctest -C Debug -VV

Test::Linux:
  stage: test
  tags:
    - linux
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .
    - ctest -C Debug -V

Build::MacOS:
  stage: build
  needs: ["Test::MacOS"]
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -G Xcode
    - ../Scripts/macos-build.sh Release
    - ctest -C Release -VV

Build::Windows:
  stage: build
  needs: ["Test::Windows"]
  tags:
    - windows
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 17 2022" -A x64 -DTIMESTAMP_SERVER_URL="http://timestamp.digicert.com"
    - cmake --build . --config Release
    - move-item -path ".\Partiels-install.exe" -destination "..\"
    - ctest -C Release -VV
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Partiels-install.exe
    expire_in: 1 week

Build::Linux:
  stage: build
  needs: ["Test::Linux"]
  tags:
    - linux
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - ctest -C Release -V
    - $CI_PROJECT_DIR/Scripts/linux-package.sh $CI_PROJECT_DIR/Partiels
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Partiels/
    expire_in: 1 week

Format:
  stage: format
  tags:
    - osx
  needs: []
  before_script:
    - brew install clang-format
  script:
    - find Source -iname *.h -o -iname *.cpp | xargs clang-format --Werror --dry-run --verbose -style=file
    - find Dependencies/Misc/Source -iname *.h -o -iname *.cpp | xargs clang-format --Werror --dry-run --verbose -style=file
    - find VampPlugins -iname *.h -o -iname *.cpp | xargs clang-format --Werror --dry-run --verbose -style=file

Doc:
  stage: doc
  tags:
    - osx
  needs: []
  before_script:
    - npm install mdpdf -g
  script:
    - mdpdf Docs/Partiels-Manual.md
    - mv Docs/Partiels-Manual.pdf ./Partiels-Manual.pdf
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Partiels-Manual.pdf
    expire_in: 1 week
