
stages:
  - test
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Test::Windows:
  stage: test
  tags:
    - windows
  script:
    - cd $CI_PROJECT_DIR
    - mkdir debug
    - cd debug
    - cmake .. -G "Visual Studio 16 2019" -A x64
    - cmake --build . --config Debug
    - ctest -C Debug

Test::Linux:
  stage: test
  tags:
    - linux
  script:
    - cd $CI_PROJECT_DIR
    - mkdir debug
    - cd debug
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . -j 3
    - ctest -C Debug

Build::Windows:
  stage: build
  needs: ["Test::Windows"]
  tags:
    - windows
  script:
    - cd $CI_PROJECT_DIR
    - mkdir release
    - cd release
    - cmake .. -G"Visual Studio 16 2019" -A x64
    - cmake --build . --config Release
    - ctest -C Release
  artifacts:
    paths:
      - $CI_PROJECT_DIR\release\Partiels_artefacts\Release\Partiels.exe
    expire_in: 1 week

Build::Linux:
  stage: build
  needs: ["Test::Linux"]
  tags:
    - linux
  script:
    - cd $CI_PROJECT_DIR
    - mkdir release
    - cd release
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . -j 3
    - ctest -C Release
  artifacts:
    paths:
      - $CI_PROJECT_DIR/release/Partiels_artefacts/Release/Partiels
    expire_in: 1 week

Deploy::Windows:
  stage: deploy
  needs: ["Build::Windows"]
  tags:
    - windows
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cd $CI_PROJECT_DIR\release\Partiels_artefacts\Release
    - tar.exe -a -c -f Partiels-v$CI_COMMIT_TAG-Windows-10.zip Partiels.exe
    - cp Partiels-v$CI_COMMIT_TAG-Windows-10.zip C:\Users\pierr\Nextcloud\Partiels\Alpha

Deploy::Linux:
  stage: deploy
  needs: ["Build::Linux"]
  tags:
    - linux
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cd $CI_PROJECT_DIR/release/Partiels_artefacts/Release
    - mkdir Partiels-v$CI_COMMIT_TAG
    - cp Partiels Partiels-v$CI_COMMIT_TAG
    - cp ../../../BinaryData/Icons/icon.png Partiels-v$CI_COMMIT_TAG
    - cp ../../../BinaryData/Misc/Partiels.desktop Partiels-v$CI_COMMIT_TAG
    - tar -zcvf Partiels-v$CI_COMMIT_TAG-Ubuntu-x86_64.tar.gz Partiels-v$CI_COMMIT_TAG
    - cp Partiels-v$CI_COMMIT_TAG-Ubuntu-x86_64.tar.gz /home/pierre/Nextcloud/Partiels/Alpha
