
stages:
  - test
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Test::MacOS:
  stage: test
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -G Xcode
    - cmake --build . --config Debug
    - export VAMP_PATH="$CI_PROJECT_DIR/build/Debug"
    - echo $VAMP_PATH
    - ctest -C Debug -VV

Test::Windows:
  stage: test
  tags:
    - windows
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 17 2022" -A x64
    - cmake --build . --config Debug
    - $env:VAMP_PATH="$CI_PROJECT_DIR\build\Debug"
    - echo $env:VAMP_PATH
    - ctest -C Debug -VV

Test::Ubuntu:
  stage: test
  tags:
    - linux
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .
    - export VAMP_PATH="$CI_PROJECT_DIR/build"
    - echo $VAMP_PATH
    - ctest -C Debug -V

Test::Debian:
  stage: test
  tags:
    - debian
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11
    - cmake --build .
    - export VAMP_PATH="$CI_PROJECT_DIR/build"
    - echo $VAMP_PATH
    - ctest -C Debug -V

Build::MacOS:
  stage: build
  needs: ["Test::MacOS"]
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -G Xcode
    - cmake --build . --config Release
    - export VAMP_PATH="$CI_PROJECT_DIR/build/Release"
    - echo $VAMP_PATH
    - ctest -C Release -VV

Build::Windows:
  stage: build
  needs: ["Test::Windows"]
  tags:
    - windows
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 17 2022" -A x64
    - cmake --build . --config Release
    - $env:VAMP_PATH="$CI_PROJECT_DIR\build\Release"
    - echo $env:VAMP_PATH
    - ctest -C Release -VV
    - Get-Content "$CI_PROJECT_DIR\BinaryData\Resource\About.txt", "$CI_PROJECT_DIR\BinaryData\Resource\ChangeLog.txt" | Out-File "$CI_PROJECT_DIR\build\Install.txt"
    - '& "C:/Program Files (x86)/Inno Setup 6/iscc.exe" "$CI_PROJECT_DIR\Scripts\windows-package.iss"'
    - Move-Item -Path $CI_PROJECT_DIR\build\Partiels-install.exe -Destination $CI_PROJECT_DIR\Partiels-install.exe
  artifacts:
    paths:
      - $CI_PROJECT_DIR\Partiels-install.exe
    expire_in: 1 week

Build::Ubuntu:
  stage: build
  needs: ["Test::Ubuntu"]
  tags:
    - linux
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - export VAMP_PATH="$CI_PROJECT_DIR/build"
    - ctest -C Release -V
    - $CI_PROJECT_DIR/Scripts/linux-package.sh $CI_PROJECT_DIR/Partiels
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Partiels/
    expire_in: 1 week

Build::Debian:
  stage: build
  needs: ["Test::Debian"]
  tags:
    - debian
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11
    - cmake --build .
    - export VAMP_PATH="$CI_PROJECT_DIR/build"
    - ctest -C Release -V
    - $CI_PROJECT_DIR/Scripts/linux-package.sh $CI_PROJECT_DIR/Partiels
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Partiels/
    expire_in: 1 week
