
stages:
  - test
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Test::Windows:
  stage: test
  tags:
    - windows
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 16 2019" -A x64
    - cmake --build . --config Debug
    - set $env:VAMP_PATH="$CI_PROJECT_DIR\build\Debug"
    - ctest -C Debug

Test::Ubuntu:
  stage: test
  tags:
    - linux
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .
    - export VAMP_PATH="$CI_PROJECT_DIR/build"
    - ctest -C Debug

Test::Debian:
  stage: test
  tags:
    - debian
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11
    - cmake --build .
    - export VAMP_PATH="$CI_PROJECT_DIR/build"
    - ctest -C Debug

Build::Windows:
  stage: build
  needs: ["Test::Windows"]
  tags:
    - windows
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 16 2019" -A x64
    - cmake --build . --config Release
    - set $env:VAMP_PATH="$CI_PROJECT_DIR\build\Release"
    - ctest -C Release
    - '& "C:/Program Files (x86)/Inno Setup 6/iscc.exe" "$CI_PROJECT_DIR\Scripts\windows-package.iss"'
  artifacts:
    paths:
      - $CI_PROJECT_DIR\Partiels-install.exe
    expire_in: 1 week

Build::Ubuntu:
  stage: build
  needs: ["Test::Ubuntu"]
  tags:
    - linux
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - export VAMP_PATH="$CI_PROJECT_DIR/build"
    - ctest -C Release
    - $CI_PROJECT_DIR/Scripts/linux-package.sh $CI_PROJECT_DIR/Partiels
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Partiels/
    expire_in: 1 week

Build::Debian:
  stage: build
  needs: ["Test::Debian"]
  tags:
    - debian
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11
    - cmake --build .
    - export VAMP_PATH="$CI_PROJECT_DIR/build"
    - ctest -C Release
    - $CI_PROJECT_DIR/Scripts/linux-package.sh $CI_PROJECT_DIR/Partiels
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Partiels/
    expire_in: 1 week

Deploy::Windows:
  stage: deploy
  needs: ["Build::Windows"]
  tags:
    - windows
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cd $CI_PROJECT_DIR
    - tar.exe -a -c -f Partiels-v$CI_COMMIT_TAG-Windows-10.zip Partiels-install.exe
    - cp Partiels-v$CI_COMMIT_TAG-Windows-10.zip C:\Users\pierr\Nextcloud\Partiels\Temp

Deploy::Ubuntu:
  stage: deploy
  needs: ["Build::Ubuntu"]
  tags:
    - linux
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cd $CI_PROJECT_DIR
    - tar -zcvf Partiels-v$CI_COMMIT_TAG-Ubuntu-x86_64.tar.gz Partiels
    - cp Partiels-v$CI_COMMIT_TAG-Ubuntu-x86_64.tar.gz /home/pierre/Nextcloud/Partiels/Temp

Deploy::Debian:
  stage: deploy
  needs: ["Build::Debian"]
  tags:
    - debian
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cd $CI_PROJECT_DIR
    - tar -zcvf Partiels-v$CI_COMMIT_TAG-Debian-x86_64.tar.gz Partiels
