set(VAMP_SDK_DIRECTORY "vamp-plugin-sdk")
set(VAMP_HOST_SDK_DIRECTORY "${VAMP_SDK_DIRECTORY}/vamp-hostsdk")
set(VAMP_HOST_SOURCES_DIRECTORY "${VAMP_SDK_DIRECTORY}/src/vamp-hostsdk")

file(GLOB VAMP_HOST_SDK_HEADERS ${VAMP_HOST_SDK_DIRECTORY}/*h)
file(GLOB VAMP_HOST_SDK_SOURCES ${VAMP_HOST_SOURCES_DIRECTORY}/*h  ${VAMP_HOST_SOURCES_DIRECTORY}/*cpp ${VAMP_HOST_SOURCES_DIRECTORY}/*c)

source_group("Vamp" FILES ${VAMP_HOST_SDK_HEADERS} ${VAMP_HOST_SDK_SOURCES})
add_library(vamp STATIC ${VAMP_HOST_SDK_HEADERS} ${VAMP_HOST_SDK_SOURCES})
target_include_directories(vamp PUBLIC ${VAMP_SDK_DIRECTORY})
