set(VAMP_SDK_DIRECTORY "vamp-plugin-sdk")
set(VAMP_HOST_SDK_DIRECTORY "${VAMP_SDK_DIRECTORY}/vamp-hostsdk")
set(VAMP_HOST_SOURCES_DIRECTORY "${VAMP_SDK_DIRECTORY}/src/vamp-hostsdk")

file(GLOB VAMP_HOST_SDK_HEADERS ${VAMP_HOST_SDK_DIRECTORY}/*h)
file(GLOB VAMP_HOST_SDK_SOURCES ${VAMP_HOST_SOURCES_DIRECTORY}/*h  ${VAMP_HOST_SOURCES_DIRECTORY}/*cpp ${VAMP_HOST_SOURCES_DIRECTORY}/*c)

source_group("Vamp" FILES ${VAMP_HOST_SDK_HEADERS} ${VAMP_HOST_SDK_SOURCES})
add_library(vamp STATIC ${VAMP_HOST_SDK_HEADERS} ${VAMP_HOST_SDK_SOURCES})
target_compile_definitions(vamp PUBLIC _VAMP_NO_HOST_NAMESPACE=1)
if(WIN32)
target_compile_definitions(vamp PRIVATE _USE_MATH_DEFINES)
target_compile_options(vamp PRIVATE /wd4996)
target_compile_options(vamp PRIVATE /wd4267)
elseif(APPLE)
set_target_properties(vamp PROPERTIES ARCHIVE_OUTPUT_DIRECTORY "./")
endif()
target_include_directories(vamp PUBLIC ${VAMP_SDK_DIRECTORY})

set(VAMP_EXAMPLES_DIRECTORY "${VAMP_SDK_DIRECTORY}/examples")
file(GLOB VAMP_EXAMPLE_PLUGINS_SOURCES ${VAMP_EXAMPLES_DIRECTORY}/*h  ${VAMP_EXAMPLES_DIRECTORY}/*cpp ${VAMP_EXAMPLES_DIRECTORY}/*c)
source_group("Vamp/Examples" FILES ${VAMP_EXAMPLE_PLUGINS_SOURCES})

add_library(vamp-example-plugins SHARED ${VAMP_EXAMPLE_PLUGINS_SOURCES} ${VAMP_SDK_DIRECTORY}/src/vamp-sdk/PluginAdapter.cpp ${VAMP_SDK_DIRECTORY}/src/vamp-sdk/RealTime.cpp)
target_include_directories(vamp-example-plugins PRIVATE ${VAMP_SDK_DIRECTORY})
set_target_properties(vamp-example-plugins PROPERTIES PREFIX "")
set_target_properties(vamp-example-plugins PROPERTIES LIBRARY_OUTPUT_DIRECTORY_DEBUG ${CMAKE_CURRENT_BINARY_DIR}/Debug)
set_target_properties(vamp-example-plugins PROPERTIES LIBRARY_OUTPUT_DIRECTORY_RELEASE ${CMAKE_CURRENT_BINARY_DIR}/Release)
if(WIN32)
set_target_properties(vamp-example-plugins PROPERTIES LINK_FLAGS "/export:vampGetPluginDescriptor")
target_compile_options(vamp-example-plugins PRIVATE /wd4244 /wd4267 /wd4996)
endif()
