/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

#include <cstring>

namespace TestResultsData
{

//================== PluginList.json ==================
static const unsigned char temp_binary_data_20[] =
"[\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"amplitude\",\n"
"            \"identifier\": \"vamp-example-plugins:amplitudefollower\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"acf\",\n"
"            \"identifier\": \"vamp-example-plugins:fixedtempo\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"candidates\",\n"
"            \"identifier\": \"vamp-example-plugins:fixedtempo\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"detectionfunction\",\n"
"            \"identifier\": \"vamp-example-plugins:fixedtempo\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"filtered_acf\",\n"
"            \"identifier\": \"vamp-example-plugins:fixedtempo\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"tempo\",\n"
"            \"identifier\": \"vamp-example-plugins:fixedtempo\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"detectionfunction\",\n"
"            \"identifier\": \"vamp-example-plugins:percussiononsets\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"onsets\",\n"
"            \"identifier\": \"vamp-example-plugins:percussiononsets\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"powerspectrum\",\n"
"            \"identifier\": \"vamp-example-plugins:powerspectrum\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"linearcentroid\",\n"
"            \"identifier\": \"vamp-example-plugins:spectralcentroid\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"logcentroid\",\n"
"            \"identifier\": \"vamp-example-plugins:spectralcentroid\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"counts\",\n"
"            \"identifier\": \"vamp-example-plugins:zerocrossing\"\n"
"        }\n"
"    },\n"
"    {\n"
"        \"key\": {\n"
"            \"feature\": \"zerocrossings\",\n"
"            \"identifier\": \"vamp-example-plugins:zerocrossing\"\n"
"        }\n"
"    }\n"
"]\n";

const char* PluginList_json = (const char*) temp_binary_data_20;
}
